import { Colis } from '../app/colis/colis_page';
import { Client } from '../app/client/clientPage';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'CL-001',
    name: 'Ahmed El Idrissi',
    phone: '+212 6 12 34 56 78',
    email: 'ahmed@example.com',
    city: 'Casablanca',
    address: '24 Rue de Goulmima, Bourgogne, Casablanca',
    addressMorocco: '24 Rue de Goulmima, Bourgogne, Casablanca',
    addressFrance: '142 Rue de Rivoli, 75001 Paris',
    totalShipments: 12,
    createdAt: '08/07/2026',
  },
  {
    id: 'CL-002',
    name: 'Fatima Zahra',
    phone: '+212 6 98 76 54 32',
    email: 'fatima@example.com',
    city: 'Rabat',
    address: '15 Avenue Mohammed V, Rabat',
    addressMorocco: '15 Avenue Mohammed V, Rabat',
    addressFrance: '28 Rue de la République, 69002 Lyon',
    totalShipments: 8,
    createdAt: '12/07/2026',
  },
  {
    id: 'CL-003',
    name: 'Omar Benali',
    phone: '+212 6 11 22 33 44',
    email: 'omar@example.com',
    city: 'Marrakech',
    address: '45 Avenue Mohammed VI, Marrakech',
    addressMorocco: '45 Avenue Mohammed VI, Marrakech',
    addressFrance: '10 Quai du Port, 13002 Marseille',
    totalShipments: 5,
    createdAt: '15/07/2026',
  },
  {
    id: 'CL-004',
    name: 'Yassine Khatib',
    phone: '+212 6 55 66 77 88',
    email: 'yassine@example.com',
    city: 'Tanger',
    address: '12 Boulevard Pasteur, Tanger',
    addressMorocco: '12 Boulevard Pasteur, Tanger',
    addressFrance: '5 Boulevard Victor Hugo, 31000 Toulouse',
    totalShipments: 3,
    createdAt: '20/07/2026',
  },
  {
    id: 'CL-005',
    name: 'Imane Belkacem',
    phone: '+212 6 44 55 66 77',
    email: 'imane@example.com',
    city: 'Fès',
    address: '8 Rue Allal Ben Abdellah, Fès',
    addressMorocco: '8 Rue Allal Ben Abdellah, Fès',
    addressFrance: '18 Rue Nationale, 59800 Lille',
    totalShipments: 2,
    createdAt: '25/07/2026',
  },
];

export const INITIAL_COLIS: Colis[] = [
  {
    id: 'CX-8021',
    senderName: 'Ahmed El Idrissi',
    senderPhone: '+212 6 12 34 56 78',
    receiverName: 'Marie Dupont',
    receiverPhone: '+33 6 7890 1234',
    fromCity: 'Casablanca',
    toCity: 'Paris',
    weight: 12.5,
    price: 35,
    status: 'in_transit',
    date: '06/08/2026',
    description: 'Vêtements et produits d’artisanat.',
  },
  {
    id: 'CX-3940',
    senderName: 'Fatima Zahra',
    senderPhone: '+212 6 98 76 54 32',
    receiverName: 'Jean-Pierre Martin',
    receiverPhone: '+33 6 1234 5678',
    fromCity: 'Rabat',
    toCity: 'Lyon',
    weight: 8.2,
    price: 24,
    status: 'pending',
    date: '07/08/2026',
    description: 'Livres et matériel informatique.',
  },
  {
    id: 'CX-1032',
    senderName: 'Omar Benali',
    senderPhone: '+212 6 11 22 33 44',
    receiverName: 'Karim Bensalah',
    receiverPhone: '+212 6 9876 5432',
    fromCity: 'Marrakech',
    toCity: 'Marseille',
    weight: 22.0,
    price: 65,
    status: 'delivered',
    date: '01/08/2026',
    description: 'Électroménager et huile d’argan.',
  },
  {
    id: 'CX-4950',
    senderName: 'Ahmed El Idrissi',
    senderPhone: '+212 6 12 34 56 78',
    receiverName: 'Pierre Bernard',
    receiverPhone: '+33 6 5432 1098',
    fromCity: 'Casablanca',
    toCity: 'Bordeaux',
    weight: 18.0,
    price: 52,
    status: 'delivered',
    date: '02/08/2026',
    description: 'Huile d’olive et gâteaux marocains.',
  },
];
